"""
hardware/muse_reader.py
------------------------
Muse EEG headset interface using Lab Streaming Layer (LSL / pylsl).

Pairing instructions
--------------------
1. Download and install the Muse app (iOS/Android) and enable Bluetooth.
2. Install `muse-lsl` (https://github.com/alexandrebarachant/muse-lsl):
       pip install muse-lsl
3. Start streaming from a terminal:
       muselsl stream --address <MUSE_MAC_ADDRESS>
   (Find the MAC address via `muselsl list`)
4. Verify the stream is visible:
       muselsl view
5. Once streaming, run this module — it will discover the LSL inlet
   automatically.

If no device is found the functions fall back to simulated EEG data
generated by `data.simulate_eeg`.

Dependencies:
    pip install pylsl
"""

import sys
import warnings
from pathlib import Path
from typing import Optional

import numpy as np

# Resolve project root for sibling-package imports
_HERE = Path(__file__).resolve().parent
_ROOT = _HERE.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

# pylsl is optional — graceful fallback if not installed
try:
    from pylsl import StreamInlet, resolve_byprop  # type: ignore
    _LSL_AVAILABLE = True
except ImportError:
    _LSL_AVAILABLE = False
    warnings.warn(
        "pylsl is not installed. Muse reader will use simulated data. "
        "Install with: pip install pylsl",
        ImportWarning,
        stacklevel=2,
    )

# Default Muse parameters
MUSE_N_CHANNELS: int = 4   # TP9, AF7, AF8, TP10
MUSE_FS: int = 256         # Sampling frequency in Hz

# Module-level inlet cache
_inlet: Optional[object] = None


def connect_muse(timeout: float = 5.0) -> bool:
    """Connect to a Muse headset via LSL.

    Searches for an active EEG stream broadcast by `muselsl stream`.
    Caches the inlet for subsequent `read_epoch` calls.

    Args:
        timeout: Seconds to wait while searching for a stream (default: 5 s).

    Returns:
        True if a real device was found, False if falling back to simulation.
    """
    global _inlet

    if not _LSL_AVAILABLE:
        print("[Muse] pylsl not available — will use simulated data.")
        return False

    print(f"[Muse] Searching for EEG stream (timeout={timeout}s) …")
    streams = resolve_byprop("type", "EEG", timeout=timeout)

    if not streams:
        print("[Muse] No LSL EEG stream found — will use simulated data.")
        return False

    _inlet = StreamInlet(streams[0])
    info = _inlet.info()
    print(
        f"[Muse] Connected to '{info.name()}' "
        f"({info.channel_count()} ch @ {info.nominal_srate()} Hz)"
    )
    return True


def read_epoch(duration: float = 2.0) -> np.ndarray:
    """Read a fixed-length EEG epoch from the Muse headset.

    If no real device is connected, returns a simulated epoch with the same
    shape using `data.simulate_eeg.generate_multiclass_eeg`.

    Args:
        duration: Epoch length in seconds (default: 2 s).

    Returns:
        epoch: numpy array of shape (n_channels, n_timepoints) — float32.
               n_channels = 4 for real Muse; 8 for simulated fallback.
    """
    if _inlet is None:
        return _simulated_epoch(duration=duration)

    n_samples_needed = int(MUSE_FS * duration)
    samples = []

    while len(samples) < n_samples_needed:
        chunk, _ = _inlet.pull_chunk(timeout=1.0, max_samples=n_samples_needed)
        if chunk:
            samples.extend(chunk)

    # Trim to exact length and transpose to (n_channels, n_timepoints)
    arr = np.array(samples[:n_samples_needed], dtype=np.float32).T
    return arr


def _simulated_epoch(n_channels: int = 4, duration: float = 2.0) -> np.ndarray:
    """Return a single simulated EEG epoch as a fallback.

    Args:
        n_channels: Number of channels to simulate (default: 4, matching Muse).
        duration:   Epoch duration in seconds (default: 2 s).

    Returns:
        epoch: numpy array of shape (n_channels, n_timepoints).
    """
    from data.simulate_eeg import generate_multiclass_eeg

    signals, _ = generate_multiclass_eeg(
        n_samples=1, n_channels=n_channels, duration=duration, fs=MUSE_FS
    )
    return signals[0]


if __name__ == "__main__":
    connected = connect_muse(timeout=5.0)
    epoch = read_epoch(duration=2.0)
    print(f"Epoch shape: {epoch.shape}  (hardware={'real' if connected else 'simulated'})")
