"""
hardware/openbci_reader.py
---------------------------
OpenBCI EEG board interface using the brainflow library.

Supports:
  - Cyton board   (board_id=0, 8-channel, 250 Hz)
  - Ganglion board (board_id=1, 4-channel, 200 Hz)

If no board is detected the functions fall back to simulated EEG data
generated by `data.simulate_eeg`.

Setup instructions
------------------
1. Install brainflow:
       pip install brainflow
2. Connect the OpenBCI dongle to a USB port.
3. Power on the Cyton/Ganglion board.
4. Find the serial port (e.g. /dev/ttyUSB0 on Linux, COM3 on Windows):
       python -c "import serial.tools.list_ports; print(list(serial.tools.list_ports.comports()))"
5. Pass `serial_port` to `connect_openbci()` or let it auto-detect.

Dependencies:
    pip install brainflow
"""

import sys
import warnings
from pathlib import Path
from typing import Optional

import numpy as np

# Resolve project root for sibling-package imports
_HERE = Path(__file__).resolve().parent
_ROOT = _HERE.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

# brainflow is optional — graceful fallback if not installed
try:
    from brainflow.board_shim import BoardShim, BrainFlowInputParams  # type: ignore
    from brainflow.data_filter import DataFilter  # type: ignore
    _BRAINFLOW_AVAILABLE = True
except ImportError:
    _BRAINFLOW_AVAILABLE = False
    warnings.warn(
        "brainflow is not installed. OpenBCI reader will use simulated data. "
        "Install with: pip install brainflow",
        ImportWarning,
        stacklevel=2,
    )

# Board ID constants (mirrors brainflow.BoardIds)
CYTON_BOARD_ID: int = 0
GANGLION_BOARD_ID: int = 1

# Module-level board cache
_board: Optional[object] = None
_board_id: int = CYTON_BOARD_ID


def connect_openbci(
    board_id: int = CYTON_BOARD_ID,
    serial_port: str = "",
) -> bool:
    """Connect to an OpenBCI board via brainflow.

    Starts the data stream and caches the board object for `read_epoch`.

    Args:
        board_id:    Board type — 0 for Cyton, 1 for Ganglion (default: 0).
        serial_port: Serial port path (e.g. '/dev/ttyUSB0').
                     Leave empty to let brainflow auto-detect.

    Returns:
        True if a real board was connected, False if falling back to simulation.
    """
    global _board, _board_id

    if not _BRAINFLOW_AVAILABLE:
        print("[OpenBCI] brainflow not available — will use simulated data.")
        return False

    _board_id = board_id
    board_name = "Cyton" if board_id == CYTON_BOARD_ID else "Ganglion"

    try:
        params = BrainFlowInputParams()
        if serial_port:
            params.serial_port = serial_port

        board = BoardShim(board_id, params)
        board.prepare_session()
        board.start_stream()
        _board = board
        print(f"[OpenBCI] Connected to {board_name} board (id={board_id})")
        return True

    except Exception as exc:  # noqa: BLE001
        print(f"[OpenBCI] Could not connect to {board_name}: {exc}")
        print("[OpenBCI] Falling back to simulated data.")
        _board = None
        return False


def read_epoch(duration: float = 2.0) -> np.ndarray:
    """Read a fixed-length EEG epoch from the OpenBCI board.

    If no real board is connected, returns a simulated epoch with the same
    shape using `data.simulate_eeg.generate_multiclass_eeg`.

    Args:
        duration: Epoch length in seconds (default: 2 s).

    Returns:
        epoch: numpy array of shape (n_channels, n_timepoints) — float32.
    """
    if _board is None:
        return _simulated_epoch(duration=duration)

    try:
        fs = BoardShim.get_sampling_rate(_board_id)
        n_samples_needed = int(fs * duration)

        # Poll until enough samples are buffered
        import time
        while _board.get_board_data_count() < n_samples_needed:
            time.sleep(0.05)

        data = _board.get_board_data(n_samples_needed)
        eeg_channels = BoardShim.get_eeg_channels(_board_id)
        epoch = data[eeg_channels, :n_samples_needed].astype(np.float32)
        return epoch

    except Exception as exc:  # noqa: BLE001
        print(f"[OpenBCI] Error reading data: {exc} — using simulated data.")
        return _simulated_epoch(duration=duration)


def disconnect_openbci() -> None:
    """Stop streaming and release the board session."""
    global _board
    if _board is not None and _BRAINFLOW_AVAILABLE:
        try:
            _board.stop_stream()
            _board.release_session()
            print("[OpenBCI] Board disconnected.")
        except Exception:  # noqa: BLE001
            pass
        _board = None


def _simulated_epoch(duration: float = 2.0) -> np.ndarray:
    """Return a single simulated EEG epoch as a fallback.

    Args:
        duration: Epoch duration in seconds (default: 2 s).

    Returns:
        epoch: numpy array of shape (8, n_timepoints).
    """
    from data.simulate_eeg import generate_multiclass_eeg

    signals, _ = generate_multiclass_eeg(
        n_samples=1, n_channels=8, duration=duration, fs=256
    )
    return signals[0]


if __name__ == "__main__":
    connected = connect_openbci(board_id=CYTON_BOARD_ID)
    epoch = read_epoch(duration=2.0)
    print(f"Epoch shape: {epoch.shape}  (hardware={'real' if connected else 'simulated'})")
    if connected:
        disconnect_openbci()
